# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cdbabf93ffaec38a10a777369cffcb8de2604e8ce5d31c224caa5ada2221ff1d15f59aff8cd9fa3d741a08a7f5244e47b8c18d74ccf406bc164bf0da7081512

test:
  secret_key_base: d8322af26606f99d092a77b29eb13f8fc107b9cdda9f43ff3fa7b44bb94d953f6d56ee5e1f9e23995251c275d26971160619bbd7a8ac9ad41721b8694f93261a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
